import Head from "next/head";
import Rending from "../src/components/units/newsMoa/rending/rending";

export default function RendingPage(): JSX.Element {
  return (
    <>
      <Head>
        <title>NewsMoa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Rending />
    </>
  );
}
